In [2]:
import numpy as np
def merge_neighbors(distance_matrix, nodes):
    current_nodes=nodes[:]
    print(current_nodes)
    sums = []
    for i in range(len(distance_matrix)):
        row_sum = 0
        for j in range(len(distance_matrix[i])):
            row_sum += distance_matrix[i][j]
        sums.append(row_sum)
        
    L=len(nodes) 
    adjusted_dm=np.zeros((L,L))
    for i in range(L):
        for j in range(L):
            adjusted_dm[i][j]=(L-2)*distance_matrix[i][j]-sums[i]-sums[j]
    for i in range(L):
        adjusted_dm[i][i]=0
        
    print(adjusted_dm)
    minimum=np.min(adjusted_dm) 
    row=np.argwhere(adjusted_dm == minimum)[0][0] 
    column=np.argwhere(adjusted_dm == minimum)[0][1] 
    

    print( nodes[row] + " and " + nodes[column]+ " are merged")
    node_a=nodes[row]  
    node_b=nodes[column] 
    merged_node=nodes[row] + nodes[column]   
    del nodes[column] 
    del nodes[row] 
    nodes=[merged_node]+nodes
    L=len(nodes)

    
    d_r=0.5*(distance_matrix[row][column]+distance_matrix[row][column+1]-distance_matrix[column][column+1])
    d_c=distance_matrix[row][column]-d_r
    print(f"Distance of {node_a} from {merged_node} = {d_r}")
    print(f"Distance of {node_b} from {merged_node} = {d_c}")


    L=len(nodes)
    to_delete=[row,column]
    temp_d_row= np.delete(distance_matrix, to_delete, axis=0)
    temp_d_column=np.delete(temp_d_row, to_delete, axis=1)
    initial_new_dm=temp_d_column
    initial_new_dm=initial_new_dm.tolist()
    
    
    

    initial_new_dm = [[0] + row for row in initial_new_dm]
    

    initial_new_dm.insert(0, [0, 0, 0, 0])
    
    
    for j in range(1,L):
        for q in range(len(current_nodes)):
            if (nodes[j]==current_nodes[q]):
                print(current_nodes[q],distance_matrix[row][q],q)
                initial_new_dm[0][j]=initial_new_dm[0][j]+distance_matrix[row][q]-d_r
                initial_new_dm[j][0]=initial_new_dm[0][j]

    print(initial_new_dm)
    final_distance_matrix=initial_new_dm
    
    return final_distance_matrix,nodes
    

    
x1,x2=merge_neighbors(dm,nodes)

y1,y2=merge_neighbors(x1,x2)

['a', 'b', 'c', 'd', 'e']
[[  0. -50. -38. -34. -34.]
 [-50.   0. -38. -34. -34.]
 [-38. -38.   0. -40. -40.]
 [-34. -34. -40.   0. -48.]
 [-34. -34. -40. -48.   0.]]
a and b are merged
Distance of a from ab = 2.0
Distance of b from ab = 3.0
c 9 2
d 9 3
e 8 4
[[0, 7.0, 7.0, 6.0], [7.0, 0, 8, 7], [7.0, 8, 0, 3], [6.0, 7, 3, 0]]
['ab', 'c', 'd', 'e']
[[  0. -28. -24. -24.]
 [-28.   0. -24. -24.]
 [-24. -24.   0. -28.]
 [-24. -24. -28.   0.]]
ab and c are merged
Distance of ab from abc = 3.0
Distance of c from abc = 4.0
d 7.0 2
e 6.0 3
[[0, 4.0, 3.0, 0], [4.0, 0.0, 3.0], [3.0, 3.0, 0.0]]


In [1]:
dm=[[0, 5, 9, 9, 8],
    [5, 0, 10, 10, 9],
    [9, 10, 0, 8, 7],
    [9, 10, 8, 0, 3],
    [8, 9, 7, 3, 0]
   ]

nodes=['a','b','c','d','e']